---
Name: 'silverstripe-forager-subsites'
After: '#silverstripe-forager'
---
SilverStripe\Forager\Service\IndexConfiguration:
  extensions:
    - SilverStripe\ForagerSubsites\Extensions\IndexConfigurationExtension
SilverStripe\Forager\Admin\SearchAdmin:
  extensions:
    - SilverStripe\ForagerSubsites\Extensions\SearchAdminExtension
SilverStripe\Forager\Jobs\ReindexJob:
  extensions:
    - SilverStripe\ForagerSubsites\Extensions\IndexJobExtension
SilverStripe\Forager\Jobs\IndexJob:
  extensions:
    - SilverStripe\ForagerSubsites\Extensions\IndexJobExtension
