---
Name: 'silverstripe-forager-subsites'
After: '#silverstripe-forager'
---
SilverStripe\Forager\Extensions\SearchServiceExtension:
  extensions:
    SubsiteSearchServiceExtension: SilverStripe\ForagerSubsites\Extensions\SubsiteSearchServiceExtension
SilverStripe\Forager\Service\IndexConfiguration:
  extensions:
    SubsiteIndexConfigurationExtension: SilverStripe\ForagerSubsites\Extensions\IndexConfigurationExtension
SilverStripe\Forager\Admin\SearchIndexAdmin:
  extensions:
    SubsiteSearchAdminExtension: SilverStripe\ForagerSubsites\Extensions\SearchAdminExtension
SilverStripe\Forager\Jobs\ReindexJob:
  extensions:
    SubsiteIndexJobExtension: SilverStripe\ForagerSubsites\Extensions\IndexJobExtension
SilverStripe\Forager\Jobs\IndexJob:
  extensions:
    SubsiteIndexJobExtension: SilverStripe\ForagerSubsites\Extensions\IndexJobExtension
